// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EverythingError = "Ok" | "Memory" | "Ipc" | "RegisterClassEx" | "CreateWindow" | "CreateThread" | "InvalidIndex" | "InvalidCall" | "InvalidRequest" | "InvalidParameter";